#!/bin/sh
rm ~/.config/rofi -r
rm ~/.config/nvim -r
rm ~/.config/compton -r

ln -sf $PWD/rofi $HOME/.config/rofi
ln -sf $PWD/nvim $HOME/.config/nvim
ln -sf $PWD/compton $HOME/.config/compton

# nvim --cmd PlugInstall
