#!/bin/dash
engines="xkb:us::eng Bamboo"
switch() {
	numarg=$#
	count=0
	for n in "$@";
	do
		count=$(( count + 1 ))
		[ $(ibus engine) = $n ] && break
	done
	ibus engine $(echo $engines | cut -d ' ' -f $(( count  % numarg + 1)))
}
switch $engines
