#!/bin/sh
if [ -z "$1" ]; then
    f="root.latex";
else
    f=$1;
fi
echo "pdf:
\tlualatex $f
\tpkill -HUP mupdf
preview:
\tmupdf $(basename $f).pdf 2> /dev/null &
\tdisown
bib:
\tbibtex $(basename $f)
clean:
\trm *.{log,aux,toc,bbl}"
