#!/bin/dash
screen1=$(swaymsg -t get_outputs | jq .'[0]')
screen2=$(swaymsg -t get_outputs | jq .'[1]')
screen1_name=$(echo $screen1 | jq .'["name"]')
screen2_name=$(echo $screen2 | jq .'["name"]')
screen1_current_workspace=$(echo $screen1 | jq .'["current_workspace"]')
screen2_current_workspace=$(echo $screen2 | jq .'["current_workspace"]')
screen1_focused=$(echo $screen1 | jq .'["focused"]' | grep true)
screen2_focused=$(echo $screen2 | jq .'["focused"]' | grep true)

[ $screen1_focused ] && swaymsg workspace $screen2_current_workspace
[ $screen2_focused ] && swaymsg workspace $screen1_current_workspace
