#!/bin/dash
[ -d XBPS ] && yes | rm -r XBPS
[ -f XBPS ] && mv XBPS XBPS.file
[ -f xbps-static-latest.x86_64-musl.tar.xz ] && rm xbps-static-latest.x86_64-musl.tar.xz
wget http://alpha.de.repo.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
mkdir $PWD/XBPS
tar xvf xbps-static-latest.x86_64-musl.tar.xz -C $PWD/XBPS
export PATH=$PWD/XBPS/usr/bin:$PATH
sudo chown root:xbuilder $PWD/XBPS/usr/bin/xbps-uchroot.static
sudo chmod 4750 $PWD/XBPS/usr/bin/xbps-uchroot.static

