active-opacity = 1.000000;
animations: (
    { preset = "appear"; triggers = [ "open" ]; },
    { preset = "disappear"; triggers = [  "close" ]; },
    { direction = "down"; preset = "fly-out"; triggers = [  "hide" ]; },
    { direction = "down"; preset = "fly-in"; triggers = [  "show" ]; },
);
backend = "glx";
fade-delta = 10;
fade-exclude = [  ];
fade-in-step = 0.050000;
fade-out-step = 0.050000;
fading = false;
inactive-opacity = 1.000000;
opacity-rule = [  ];
shadow = false;
shadow-exclude = [  ];
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.750000;
vsync = true;
wintypes: { dropdown_menu = { opacity = 1.000000; }; popup_menu = { opacity = 1.000000; }; };

rules: ({
  match = "class_i='spectacle' || class_i='gscreenshot'";
  animations = (
    {
        triggers = [ "open", "show" ];
        duration = 0;
    },
    {
        triggers = [ "close", "hide" ];
        duration = 0;
    }
  );
})
